version: '3'

services:
  
  g-broker:
    build:
      context: ./../g-broker
      dockerfile: ./../g-broker/Dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1

  g-authen:
    build:
      context: ./../g-authen
      dockerfile: ./../g-authen/Dockerfile
    restart: always
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"

  g-logger:
    build:
      context: ./../g-logger
      dockerfile: ./../g-logger/Dockerfile
    restart: always
    ports:
      - "8082:80"
    deploy:
      mode: replicated
      replicas: 1

  g-mail:
    build:
      context: ./../g-mail
      dockerfile: ./../g-mail/Dockerfile
    restart: always
    ports:
      - "8083:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_ENCRYPTION: none
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      FROM_NAME: "Quang Le"
      FROM_ADDRESS: "quang.le@example.com"

  g-listener:
    build:
      context: ./../g-listener
      dockerfile: ./../g-listener/Dockerfile
    restart: always
    ports:
      - "8084:80"
    deploy:
      mode: replicated
      replicas: 1

  postgres:
      image: 'postgres:14.2'
      ports:
        - "5432:5432"
      deploy:
        mode: replicated
        replicas: 1
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: users
      volumes:
        - ./db/postgres/:/var/lib/postgresql/data/

  mongo:
      image: 'mongo:4.2.16-bionic'
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_DATABASE: logs
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: password
      volumes:
        - ./db/mongo/:/data/db

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"

  rabbitmq:
    image: 'rabbitmq:3.9-alpine'
    ports:
      - "5672:5672"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./db/rabbitmq/:/var/lib/rabbitmq